CREATE DATABASE SenaTur_Tarde;

USE SenaTur_Tarde;

CREATE TABLE Pacotes(
	PacoteId INT IDENTITY PRIMARY KEY,
	NomePacote VARCHAR(200) NOT NULL UNIQUE,
	Descricao TEXT,
	DataIda DATETIME NOT NULL,
	DataVolta DATETIME,
	Valor DECIMAL NOT NULL,
	Ativo BIT NOT NULL,
	NomeCidade VARCHAR(200) NOT NULL
);

CREATE TABLE Usuarios(
	UsuarioId INT IDENTITY PRIMARY KEY,
	Email VARCHAR(200) NOT NULL UNIQUE,
	Senha VARCHAR(100) NOT NULL,
	TipoUsuario VARCHAR(100) NOT NULL
);